name: Update README

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
runs:
  using: 'node16'
  main: 'main.js'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update the Vincenzo Marrazzo's README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}